app:
  name: "licf"

logo:
  show: false

file:
  recursion: true
  print: false
  supported-format: ["json"]
  ignore: ['.git', 'config.yaml','.idea','.settings','.classpath','target','config']
  only: ['headers.json']